Repository boostcampwm-2022/android03-Promise, pull requests merged in 2022-11, with the labels that each got.

#18 앱 아이콘, 이름 설정
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
  app/src/main/res/values/strings.xml
Labels: design

#17 Splash screen 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/ui/start/StartActivity.kt
  app/src/main/res/drawable/ic_splash_background.xml
  app/src/main/res/drawable/ic_splash_foreground.xml
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/mipmap-anydpi-v26/ic_splash.xml
  app/src/main/res/mipmap-hdpi/ic_splash.png
  app/src/main/res/mipmap-mdpi/ic_splash.png
  app/src/main/res/mipmap-xhdpi/ic_splash.png
  app/src/main/res/mipmap-xxhdpi/ic_splash.png
  app/src/main/res/mipmap-xxxhdpi/ic_splash.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: feature, design

#28 약속 추가 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/MainApplication.kt
  app/src/main/java/com/boosters/promise/data/database/PromiseDao.kt
  app/src/main/java/com/boosters/promise/data/database/PromiseDatabase.kt
  app/src/main/java/com/boosters/promise/data/database/UserTypeConverter.kt
  app/src/main/java/com/boosters/promise/data/network/PromiseService.kt
  app/src/main/java/com/boosters/promise/data/network/Retrofit.kt
  app/src/main/java/com/boosters/promise/data/promise/Place.kt
  app/src/main/java/com/boosters/promise/data/promise/Promise.kt
  app/src/main/java/com/boosters/promise/data/promise/di/DataSourceModule.kt
  app/src/main/java/com/boosters/promise/data/promise/di/InterfaceModule.kt
  app/src/main/java/com/boosters/promise/data/promise/source/PromiseRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/promise/source/local/PromiseLocalDataSource.kt
  app/src/main/java/com/boosters/promise/data/promise/source/local/PromiseLocalDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PlaceResponse.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRepository.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/user/User.kt
  app/src/main/java/com/boosters/promise/ui/promise/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/ui/promise/PromiseSettingViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promise/SearchAddressDialogFragment.kt
  app/src/main/java/com/boosters/promise/ui/promise/adapter/SearchAddressListAdapter.kt
  app/src/main/java/com/boosters/promise/util/LocalMapper.kt
  app/src/main/res/drawable/ic_add_member.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_clock.xml
  app/src/main/res/drawable/ic_marker.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_promise_setting.xml
  app/src/main/res/layout/dialog_search_address.xml
  app/src/main/res/layout/item_promise_member.xml
  app/src/main/res/layout/item_search_address_result.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: feature, design

#29 친구 목록 표시 기능 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/data/database/UserDataBase.kt
  app/src/main/java/com/boosters/promise/data/invite/FriendRepository.kt
  app/src/main/java/com/boosters/promise/data/invite/FriendRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/invite/di/DataModule.kt
  app/src/main/java/com/boosters/promise/data/invite/source/local/FriendLocalDataSource.kt
  app/src/main/java/com/boosters/promise/data/invite/source/local/FriendLocalDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/invite/source/local/UserDao.kt
  app/src/main/java/com/boosters/promise/data/invite/source/local/UserEntity.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteActivity.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteAdapter.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteDiffItemCallback.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteViewModel.kt
  app/src/main/java/com/boosters/promise/ui/model/UserUiState.kt
  app/src/main/java/com/boosters/promise/util/BindingAdapter.kt
  app/src/main/res/drawable/button_confirm.xml
  app/src/main/res/drawable/ic_member_delete.png
  app/src/main/res/drawable/ic_profile_image.png
  app/src/main/res/layout/activity_invite.xml
  app/src/main/res/layout/item_invite_member.xml
  app/src/main/res/layout/item_invite_member_info.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: feature, design

#31 약속 추가 다이얼로그 리팩토링
  app/src/main/java/com/boosters/promise/data/database/PromiseDatabase.kt
  app/src/main/java/com/boosters/promise/data/network/HeaderInterceptor.kt
  app/src/main/java/com/boosters/promise/data/network/NaverPlaceService.kt
  app/src/main/java/com/boosters/promise/data/network/PromiseService.kt
  app/src/main/java/com/boosters/promise/data/network/Retrofit.kt
  app/src/main/java/com/boosters/promise/data/place/Place.kt
  app/src/main/java/com/boosters/promise/data/place/PlaceRepository.kt
  app/src/main/java/com/boosters/promise/data/place/PlaceRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/place/di/NaverSearchApiModule.kt
  app/src/main/java/com/boosters/promise/data/place/di/PlaceModule.kt
  app/src/main/java/com/boosters/promise/data/place/source/remote/PlaceRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/place/source/remote/PlaceRemoteDateSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/place/source/remote/PlaceResponse.kt
  app/src/main/java/com/boosters/promise/data/promise/Place.kt
  app/src/main/java/com/boosters/promise/data/promise/Promise.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepository.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/promise/di/DataSourceModule.kt
  app/src/main/java/com/boosters/promise/data/promise/di/InterfaceModule.kt
  app/src/main/java/com/boosters/promise/data/promise/source/local/PromiseDao.kt
  app/src/main/java/com/boosters/promise/data/promise/source/local/UserTypeConverter.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/ui/place/PlaceSearchDialogFragment.kt
  app/src/main/java/com/boosters/promise/ui/place/PlaceSearchViewModel.kt
  app/src/main/java/com/boosters/promise/ui/place/adapter/PlaceSearchListAdapter.kt
  app/src/main/java/com/boosters/promise/ui/place/model/PlaceUiState.kt
  app/src/main/java/com/boosters/promise/ui/promise/Event.kt
  app/src/main/java/com/boosters/promise/ui/promise/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/ui/promise/PromiseSettingViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promise/SearchAddressDialogFragment.kt
  app/src/main/java/com/boosters/promise/ui/promise/model/PromiseUiState.kt
  app/src/main/java/com/boosters/promise/util/LocalMapper.kt
  app/src/main/res/layout/activity_promise_setting.xml
  app/src/main/res/layout/dialog_place_search.xml
Labels: refactor

#34 회원가입 기능 구현
  app/build.gradle
  app/src/androidTest/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSourceImplTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/PromiseApplication.kt
  app/src/main/java/com/boosters/promise/data/user/Location.kt
  app/src/main/java/com/boosters/promise/data/user/User.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepository.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/user/di/UserModule.kt
  app/src/main/java/com/boosters/promise/data/user/source/local/MyInfoLocalDataSource.kt
  app/src/main/java/com/boosters/promise/data/user/source/local/MyInfoLocalDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserBody.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/ui/model/SignUpUiState.kt
  app/src/main/java/com/boosters/promise/ui/signup/SignUpActivity.kt
  app/src/main/java/com/boosters/promise/ui/signup/SignUpViewModel.kt
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature, refactor, design

#37 사이즈 및 스타일 정의
  app/src/main/res/drawable/button_confirm.xml
  app/src/main/res/drawable/ic_member_delete.png
  app/src/main/res/drawable/ic_member_delete.xml
  app/src/main/res/drawable/ic_profile_image.png
  app/src/main/res/drawable/ic_profile_image.xml
  app/src/main/res/layout/activity_invite.xml
  app/src/main/res/layout/activity_promise_setting.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/item_invite_member.xml
  app/src/main/res/layout/item_invite_member_info.xml
  app/src/main/res/layout/item_promise.xml
  app/src/main/res/layout/item_promise_member.xml
  app/src/main/res/layout/item_search_address_result.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: design

#38 시작화면, 회원가입 화면 이동 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/MainApplication.kt
  app/src/main/java/com/boosters/promise/data/promise/Promise.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseBody.kt
  app/src/main/java/com/boosters/promise/data/user/User.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepository.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/user/source/local/MyInfoLocalDataSource.kt
  app/src/main/java/com/boosters/promise/data/user/source/local/MyInfoLocalDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteActivity.kt
  app/src/main/java/com/boosters/promise/ui/invite/model/UserUiState.kt
  app/src/main/java/com/boosters/promise/ui/promise/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/ui/promise/PromiseSettingViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promise/model/PromiseUiState.kt
  app/src/main/java/com/boosters/promise/ui/signup/SignUpActivity.kt
  app/src/main/java/com/boosters/promise/ui/signup/SignUpViewModel.kt
  app/src/main/java/com/boosters/promise/ui/signup/model/SignUpUiState.kt
  app/src/main/java/com/boosters/promise/ui/start/StartActivity.kt
  app/src/main/java/com/boosters/promise/ui/start/StartViewModel.kt
  app/src/main/java/com/boosters/promise/ui/start/adapter/PromiseListAdapter.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/layout/item_promise_member.xml
Labels: bug, feature, refactor, design

#40 splash scree 버그 해결
  app/src/main/java/com/boosters/promise/ui/start/StartActivity.kt
Labels: bug

#45 약속 설정 텍스트 짤림 현상 수정, 잘못된 파일 위치 이동
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/promise/di/InterfaceModule.kt
  app/src/main/java/com/boosters/promise/data/promise/source/PromiseRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSourceImpl.kt
  app/src/main/res/layout/activity_promise_setting.xml
Labels: bug

#47 약속 정보 설정 화면 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/ui/place/adapter/PlaceSearchListAdapter.kt
  app/src/main/java/com/boosters/promise/ui/promise/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/ui/promise/PromiseSettingViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promise/adapter/PromiseMemberListAdapter.kt
  app/src/main/res/layout/activity_promise_setting.xml
Labels: refactor, design

#51 회원가입 UiState 관련 리펙토링 및 회원가입 에러 표시 기능 추가
  app/src/main/java/com/boosters/promise/data/user/UserRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/ui/signup/SignUpActivity.kt
  app/src/main/java/com/boosters/promise/ui/signup/SignUpViewModel.kt
  app/src/main/java/com/boosters/promise/ui/signup/model/NameInputUiState.kt
  app/src/main/java/com/boosters/promise/ui/signup/model/SignUpUiState.kt
  app/src/main/java/com/boosters/promise/ui/start/StartActivity.kt
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: bug, feature, refactor

#56 약속 정보 선택 기능 수정 및 개선
  app/src/main/java/com/boosters/promise/data/model/Location.kt
  app/src/main/java/com/boosters/promise/data/place/Place.kt
  app/src/main/java/com/boosters/promise/data/place/source/remote/PlaceResponse.kt
  app/src/main/java/com/boosters/promise/data/promise/Promise.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseBody.kt
  app/src/main/java/com/boosters/promise/data/user/Location.kt
  app/src/main/java/com/boosters/promise/data/user/User.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserBody.kt
  app/src/main/java/com/boosters/promise/ui/place/PlaceSearchDialogFragment.kt
  app/src/main/java/com/boosters/promise/ui/place/adapter/PlaceSearchAdapter.kt
  app/src/main/java/com/boosters/promise/ui/place/adapter/PlaceSearchListAdapter.kt
  app/src/main/java/com/boosters/promise/ui/place/model/PlaceUiState.kt
  app/src/main/java/com/boosters/promise/ui/promise/EventType.kt
  app/src/main/java/com/boosters/promise/ui/promise/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/ui/promise/PromiseSettingViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promise/model/PromiseSettingEvent.kt
  app/src/main/java/com/boosters/promise/ui/promise/model/PromiseUiState.kt
  app/src/main/res/layout/activity_promise_setting.xml
  app/src/main/res/layout/dialog_place_search.xml
  app/src/main/res/layout/item_place_search_result.xml
Labels: bug, feature, refactor

#57 네트워크 연결 검사 구현하기
  app/src/main/java/com/boosters/promise/data/network/NetworkConnectionUtil.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/user/di/UserModule.kt
  app/src/main/java/com/boosters/promise/data/user/source/local/MyInfoLocalDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/ui/signup/SignUpActivity.kt
  app/src/main/java/com/boosters/promise/ui/signup/SignUpViewModel.kt
  app/src/main/java/com/boosters/promise/ui/signup/model/SignUpUiState.kt
  app/src/main/res/values/strings.xml
Labels: feature

#61 약속 장소 검색 디바운싱 처리
  app/src/main/java/com/boosters/promise/ui/invite/InviteActivity.kt
  app/src/main/java/com/boosters/promise/ui/place/PlaceSearchDialogFragment.kt
  app/src/main/java/com/boosters/promise/ui/place/PlaceSearchViewModel.kt
  app/src/main/res/layout/item_place_search_result.xml
Labels: bug, feature

#62 약속 정보 설정 화면 상태에 따른 스낵바 띄우기
  app/src/main/java/com/boosters/promise/data/promise/Promise.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepository.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseBody.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/user/User.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promise/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/ui/promise/PromiseSettingViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promise/model/PromiseSettingUiState.kt
  app/src/main/java/com/boosters/promise/ui/promise/model/PromiseUiState.kt
  app/src/main/res/values/strings.xml
Labels: feature, refactor

#64 ktlint plugnin 추가
  .editorconfig
  app/src/main/java/com/boosters/promise/data/database/UserDataBase.kt
  app/src/main/java/com/boosters/promise/data/invite/di/DataModule.kt
  app/src/main/java/com/boosters/promise/data/invite/source/local/UserEntity.kt
  app/src/main/java/com/boosters/promise/data/network/NaverSearchService.kt
  app/src/main/java/com/boosters/promise/data/network/NetworkConnectionUtil.kt
  app/src/main/java/com/boosters/promise/data/place/source/remote/PlaceRemoteDateSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/user/User.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserBody.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteViewModel.kt
  app/src/main/java/com/boosters/promise/ui/invite/model/UserUiState.kt
  app/src/main/java/com/boosters/promise/ui/place/adapter/PlaceSearchAdapter.kt
  app/src/main/java/com/boosters/promise/ui/promise/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/ui/signup/model/NameInputUiState.kt
  app/src/main/java/com/boosters/promise/ui/signup/model/SignUpUiState.kt
  build.gradle
Labels: feature

#74 레이어별 데이터 타입 변환 위치 일관화
  app/src/main/java/com/boosters/promise/data/place/Place.kt
  app/src/main/java/com/boosters/promise/data/place/PlaceRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/place/source/remote/PlaceRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/place/source/remote/PlaceRemoteDateSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/place/source/remote/PlaceResponseBody.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/ui/place/PlaceSearchDialogFragment.kt
  app/src/main/java/com/boosters/promise/ui/place/PlaceSearchViewModel.kt
  app/src/main/java/com/boosters/promise/ui/place/adapter/PlaceSearchAdapter.kt
  app/src/main/java/com/boosters/promise/ui/place/model/PlaceUiState.kt
  app/src/main/java/com/boosters/promise/ui/promise/PromiseSettingActivity.kt
Labels: refactor

#69 초대할 멤버 선택 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/ui/invite/InviteActivity.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteViewModel.kt
  app/src/main/java/com/boosters/promise/ui/invite/adapter/FriendAdapter.kt
  app/src/main/java/com/boosters/promise/ui/invite/adapter/InviteAdapter.kt
  app/src/main/java/com/boosters/promise/ui/invite/adapter/MemberAdapter.kt
  app/src/main/java/com/boosters/promise/ui/invite/adapter/UserDiffItemCallback.kt
  app/src/main/java/com/boosters/promise/ui/invite/model/UserUiState.kt
  app/src/main/java/com/boosters/promise/ui/promise/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/util/BindingAdapter.kt
  app/src/main/res/layout/activity_invite.xml
  app/src/main/res/layout/item_invite_friend.xml
  app/src/main/res/layout/item_invite_member.xml
Labels: bug, feature

#82 약속 추가 알림
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/data/network/CloudMessagingService.kt
  app/src/main/java/com/boosters/promise/data/network/PromiseService.kt
  app/src/main/java/com/boosters/promise/data/network/Retrofit.kt
  app/src/main/java/com/boosters/promise/data/notification/NotificationRepository.kt
  app/src/main/java/com/boosters/promise/data/notification/NotificationRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/notification/di/NotificationDataSourceModule.kt
  app/src/main/java/com/boosters/promise/data/notification/di/NotificationInterfaceModule.kt
  app/src/main/java/com/boosters/promise/data/notification/source/remote/NotificationRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/notification/source/remote/NotificationRemoteDateSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/notification/source/remote/NotificationRequestBody.kt
  app/src/main/java/com/boosters/promise/data/promise/ServerKeyRepository.kt
  app/src/main/java/com/boosters/promise/data/promise/di/PromiseDataSourceModule.kt
  app/src/main/java/com/boosters/promise/data/promise/di/PromiseInterfaceModule.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/user/User.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepository.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/user/di/UserModule.kt
  app/src/main/java/com/boosters/promise/data/user/source/local/MyInfoLocalDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserBody.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/ui/invite/model/UserUiState.kt
  app/src/main/java/com/boosters/promise/ui/notification/NotificationService.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/model/PromiseSettingUiState.kt
  app/src/main/res/values/strings.xml
Labels: bug, feature, refactor

#84 약속 상세 화면에서 약속 정보 확인
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/data/model/Location.kt
  app/src/main/java/com/boosters/promise/data/promise/Promise.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseBody.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailViewModel.kt
  app/src/main/java/com/boosters/promise/ui/detail/adapter/PromiseMemberAdapter.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteActivity.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteViewModel.kt
  app/src/main/java/com/boosters/promise/ui/invite/adapter/InviteMemberAdapter.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/adapter/PromiseDailyListAdapter.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/model/PromiseUiState.kt
  app/src/main/res/layout/activity_promise_detail.xml
  app/src/main/res/layout/item_promise_detail_member.xml
  app/src/main/res/menu/menu_detail_appbar.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
  settings.gradle
Labels: feature, design

#89 약속 상세 화면 약속 수정 화면 연결
  app/src/main/java/com/boosters/promise/data/notification/NotificationRepository.kt
  app/src/main/java/com/boosters/promise/data/notification/NotificationRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/notification/source/remote/NotificationRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/notification/source/remote/NotificationRemoteDateSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/notification/source/remote/NotificationRequestBody.kt
  app/src/main/java/com/boosters/promise/data/promise/Promise.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepository.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailViewModel.kt
  app/src/main/java/com/boosters/promise/ui/notification/NotificationService.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingViewModel.kt
  app/src/main/res/layout/activity_promise_detail.xml
  app/src/main/res/layout/activity_promise_setting.xml
  app/src/main/res/layout/item_promise_card.xml
  app/src/main/res/menu/menu_detail_toolbar.xml
  app/src/main/res/values/strings.xml
Labels: bug, feature, refactor

#93 약속 알림 추가, 수정 구분
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/notification/NotificationService.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingViewModel.kt
  app/src/main/res/values/strings.xml
Labels: feature, refactor

#86 친구 리스트 화면 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/data/invite/FriendRepository.kt
  app/src/main/java/com/boosters/promise/data/invite/FriendRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/invite/source/local/FriendLocalDataSource.kt
  app/src/main/java/com/boosters/promise/data/invite/source/local/FriendLocalDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/invite/source/local/UserDao.kt
  app/src/main/java/com/boosters/promise/data/invite/source/local/UserEntity.kt
  app/src/main/java/com/boosters/promise/data/user/User.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepository.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/user/di/UserModule.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserBody.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/ui/friend/FriendActivity.kt
  app/src/main/java/com/boosters/promise/ui/friend/FriendViewModel.kt
  app/src/main/java/com/boosters/promise/ui/friend/adapter/UserListAdapter.kt
  app/src/main/java/com/boosters/promise/ui/notification/NotificationService.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingViewModel.kt
  app/src/main/res/drawable/ic_navigate_back.xml
  app/src/main/res/layout/activity_friend.xml
  app/src/main/res/layout/activity_promise_calendar.xml
  app/src/main/res/layout/item_friend_profile.xml
  app/src/main/res/values/strings.xml
Labels: feature, design

#92 위치 정보 repository 구현, 위치 정보 업데이트 service 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/data/location/GeoLocation.kt
  app/src/main/java/com/boosters/promise/data/location/LocationRepository.kt
  app/src/main/java/com/boosters/promise/data/location/LocationRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/location/di/LocationModule.kt
  app/src/main/java/com/boosters/promise/data/model/Location.kt
  app/src/main/java/com/boosters/promise/data/place/Place.kt
  app/src/main/java/com/boosters/promise/data/place/source/remote/PlaceResponseBody.kt
  app/src/main/java/com/boosters/promise/data/promise/Promise.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseBody.kt
  app/src/main/java/com/boosters/promise/data/user/User.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepository.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserBody.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/service/LocationService.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/model/PromiseUiState.kt
  app/src/main/res/values/strings.xml
Labels: feature

#96 지도에 멤버 위치 마커로 표시, 모델 리팩토링
  app/src/main/java/com/boosters/promise/data/database/UserDataBase.kt
  app/src/main/java/com/boosters/promise/data/friend/FriendRepository.kt
  app/src/main/java/com/boosters/promise/data/friend/di/FriendDataModule.kt
  app/src/main/java/com/boosters/promise/data/friend/source/local/FriendEntity.kt
  app/src/main/java/com/boosters/promise/data/location/GeoLocation.kt
  app/src/main/java/com/boosters/promise/data/place/source/remote/PlaceResponseBody.kt
  app/src/main/java/com/boosters/promise/data/promise/Promise.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepository.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/user/User.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepository.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailViewModel.kt
  app/src/main/java/com/boosters/promise/ui/detail/adapter/PromiseMemberAdapter.kt
  app/src/main/java/com/boosters/promise/ui/friend/FriendViewModel.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteActivity.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteViewModel.kt
  app/src/main/java/com/boosters/promise/ui/invite/adapter/FriendAdapter.kt
  app/src/main/java/com/boosters/promise/ui/invite/adapter/InviteMemberAdapter.kt
  app/src/main/java/com/boosters/promise/ui/invite/adapter/UserDiffItemCallback.kt
  app/src/main/java/com/boosters/promise/ui/invite/adapter/UserUiModelDiffItemCallback.kt
  app/src/main/java/com/boosters/promise/ui/invite/model/UserUiModel.kt
  app/src/main/java/com/boosters/promise/ui/notification/NotificationService.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/adapter/PromiseDailyListAdapter.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/adapter/PromiseMemberListAdapter.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/model/PromiseUiState.kt
  app/src/main/res/layout/item_invite_friend.xml
  app/src/main/res/layout/item_invite_member.xml
  app/src/main/res/layout/item_promise_card.xml
  app/src/main/res/layout/item_promise_detail_member.xml
  app/src/main/res/layout/item_promise_member.xml
Labels: feature, refactor

#97 사용하는 모델 정리
  app/src/main/java/com/boosters/promise/data/friend/FriendRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/friend/source/local/FriendDao.kt
  app/src/main/java/com/boosters/promise/data/friend/source/local/FriendLocalDataSource.kt
  app/src/main/java/com/boosters/promise/data/friend/source/local/FriendLocalDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/invite/FriendRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/invite/source/local/FriendLocalDataSource.kt
  app/src/main/java/com/boosters/promise/data/invite/source/local/FriendLocalDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/invite/source/local/UserDao.kt
  gradlew
Labels: refactor

#107 ForegroundLocationUploadService 구현 및 장소 업로드 서비스 교체
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/data/location/LocationRepository.kt
  app/src/main/java/com/boosters/promise/data/location/LocationRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepository.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/service/LocationService.kt
  app/src/main/java/com/boosters/promise/service/locationupload/LocationUploadForegroundService.kt
  app/src/main/java/com/boosters/promise/service/locationupload/LocationUploadService.kt
  app/src/main/java/com/boosters/promise/service/locationupload/LocationUploadServiceBinder.kt
  app/src/main/java/com/boosters/promise/service/locationupload/LocationUploadServiceConnection.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailViewModel.kt
  app/src/main/java/com/boosters/promise/ui/invite/model/UserUiModel.kt
Labels: bug, feature, refactor

#114 약속 수정 화면 데이터 표시 안되는 문제
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepository.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingActivity.kt
Labels: bug, refactor

#116 위치 공유 On/Off 스위치 추가
  app/src/main/java/com/boosters/promise/data/location/LocationRepository.kt
  app/src/main/java/com/boosters/promise/data/location/LocationRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/location/UserGeoLocation.kt
  app/src/main/java/com/boosters/promise/data/location/di/LocationModule.kt
  app/src/main/java/com/boosters/promise/data/location/source/remote/LocationRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/location/source/remote/UserGeoLocationBody.kt
  app/src/main/java/com/boosters/promise/data/member/Member.kt
  app/src/main/java/com/boosters/promise/data/member/MemberRepository.kt
  app/src/main/java/com/boosters/promise/data/member/MemberRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/member/di/MemberModule.kt
  app/src/main/java/com/boosters/promise/data/member/source/local/LocationSharingPermissionLocalDataSource.kt
  app/src/main/java/com/boosters/promise/data/member/source/remote/MemberBody.kt
  app/src/main/java/com/boosters/promise/data/member/source/remote/MemberRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/promise/Promise.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepository.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseBody.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepository.kt
  app/src/main/java/com/boosters/promise/data/user/UserRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/service/locationupload/LocationUploadForegroundService.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingActivity.kt
  app/src/main/res/layout/activity_promise_detail.xml
  app/src/main/res/values/strings.xml
Labels: bug, feature, design

#119 지도 카메라 이동 기능 구현, 도착한 멤버 표시
  app/src/main/java/com/boosters/promise/data/location/source/remote/LocationRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/user/User.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailViewModel.kt
  app/src/main/java/com/boosters/promise/ui/detail/adapter/PromiseMemberAdapter.kt
  app/src/main/java/com/boosters/promise/ui/detail/model/MemberUiModel.kt
  app/src/main/java/com/boosters/promise/ui/detail/util/MapManager.kt
  app/src/main/java/com/boosters/promise/ui/invite/adapter/FriendAdapter.kt
  app/src/main/java/com/boosters/promise/ui/invite/adapter/InviteMemberAdapter.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/adapter/PromiseMemberListAdapter.kt
  app/src/main/res/drawable/button_map_control.xml
  app/src/main/res/drawable/ic_destination_flag.xml
  app/src/main/res/drawable/ic_destination_marker.xml
  app/src/main/res/drawable/ic_map_overview.xml
  app/src/main/res/drawable/ic_member_marker.xml
  app/src/main/res/layout/activity_promise_detail.xml
  app/src/main/res/layout/item_invite_friend.xml
  app/src/main/res/layout/item_invite_member.xml
  app/src/main/res/layout/item_promise_detail_member.xml
  app/src/main/res/layout/item_promise_member.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature, refactor, design
