Repository boostcampwm-2022/android03-Promise, pull requests merged in 2022-12, with the labels that each got.

#122 약속 캘린더 데코레이션 및 약속 리스트 정렬
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/decorator/PromiseContainDecorator.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/decorator/PromiseSaturdayDecorator.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/decorator/PromiseSundayDecorator.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/decorator/PromiseTodayDecorator.kt
  app/src/main/res/layout/activity_promise_calendar.xml
Labels: feature, design

#127 약속 1시간 전 알림 및 서버 키 관리
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/data/alarm/Alarm.kt
  app/src/main/java/com/boosters/promise/data/alarm/AlarmRepository.kt
  app/src/main/java/com/boosters/promise/data/alarm/AlarmRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/alarm/di/AlarmDataModule.kt
  app/src/main/java/com/boosters/promise/data/alarm/source/local/AlarmDao.kt
  app/src/main/java/com/boosters/promise/data/alarm/source/local/AlarmEntity.kt
  app/src/main/java/com/boosters/promise/data/alarm/source/local/AlarmLocalDataSource.kt
  app/src/main/java/com/boosters/promise/data/alarm/source/local/AlarmLocalDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/database/AlarmDataBase.kt
  app/src/main/java/com/boosters/promise/data/network/CloudMessagingService.kt
  app/src/main/java/com/boosters/promise/data/network/NotiHeaderInterceptor.kt
  app/src/main/java/com/boosters/promise/data/notification/NotificationRepository.kt
  app/src/main/java/com/boosters/promise/data/notification/NotificationRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/notification/di/NotificationDataSourceModule.kt
  app/src/main/java/com/boosters/promise/data/notification/source/remote/NotificationRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/notification/source/remote/NotificationRemoteDateSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepository.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/promise/ServerKeyRepository.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailViewModel.kt
  app/src/main/java/com/boosters/promise/ui/notification/AlarmDirector.kt
  app/src/main/java/com/boosters/promise/ui/notification/AlarmReceiver.kt
  app/src/main/java/com/boosters/promise/ui/notification/NotificationService.kt
  app/src/main/java/com/boosters/promise/ui/notification/di/AlarmModule.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingViewModel.kt
  app/src/main/res/values/strings.xml
Labels: feature

#132 약속 상세 화면의 위치 공유 스위치로 위치 공유 Start/Stop기능 추가
  app/src/main/java/com/boosters/promise/receiver/LocationUploadReceiver.kt
  app/src/main/java/com/boosters/promise/service/locationupload/LocationUploadForegroundService.kt
  app/src/main/java/com/boosters/promise/service/locationupload/LocationUploadService.kt
  app/src/main/java/com/boosters/promise/service/locationupload/LocationUploadServiceBinder.kt
  app/src/main/java/com/boosters/promise/service/locationupload/LocationUploadServiceConnection.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailViewModel.kt
  app/src/main/java/com/boosters/promise/ui/detail/model/PromiseUploadUiState.kt
  app/src/main/java/com/boosters/promise/util/DateUtil.kt
Labels: feature

#135 컨벤션 수정
  app/src/main/java/com/boosters/promise/data/alarm/Alarm.kt
  app/src/main/java/com/boosters/promise/data/alarm/source/local/AlarmEntity.kt
  app/src/main/java/com/boosters/promise/data/network/NotiHeaderInterceptor.kt
  app/src/main/java/com/boosters/promise/data/notification/di/NotificationDataSourceModule.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailViewModel.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteActivity.kt
  app/src/main/java/com/boosters/promise/ui/notification/AlarmDirector.kt
  app/src/main/java/com/boosters/promise/ui/notification/AlarmReceiver.kt
  app/src/main/java/com/boosters/promise/ui/notification/di/AlarmModule.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingViewModel.kt
Labels: bug, refactor

#138 약속 상세 화면에서 멤버 목록이 제대로 보여지지 않는 버그 해결
  app/src/main/java/com/boosters/promise/data/user/User.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailViewModel.kt
  app/src/main/java/com/boosters/promise/ui/detail/model/MemberUiModel.kt
  app/src/main/java/com/boosters/promise/ui/detail/util/MapManager.kt
Labels: bug

#151 부팅 후 알람 재등록
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/data/alarm/Alarm.kt
  app/src/main/java/com/boosters/promise/data/alarm/AlarmRepository.kt
  app/src/main/java/com/boosters/promise/data/alarm/AlarmRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/alarm/di/AlarmDataModule.kt
  app/src/main/java/com/boosters/promise/data/alarm/source/local/AlarmDao.kt
  app/src/main/java/com/boosters/promise/data/alarm/source/local/AlarmEntity.kt
  app/src/main/java/com/boosters/promise/data/alarm/source/local/AlarmLocalDataSource.kt
  app/src/main/java/com/boosters/promise/data/alarm/source/local/AlarmLocalDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/data/database/AlarmDataBase.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailViewModel.kt
  app/src/main/java/com/boosters/promise/ui/notification/AlarmDirector.kt
  app/src/main/java/com/boosters/promise/ui/notification/AlarmReceiver.kt
  app/src/main/java/com/boosters/promise/ui/notification/BootService.kt
  app/src/main/java/com/boosters/promise/ui/notification/NotificationService.kt
  app/src/main/java/com/boosters/promise/ui/notification/di/AlarmModule.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingViewModel.kt
  app/src/main/res/values/strings.xml
Labels: feature, refactor

#158 다크모드 적용 및 세로모드 고정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarActivity.kt
  app/src/main/res/drawable/bg_calendar_today_circle.xml
  app/src/main/res/drawable/button_confirm.xml
  app/src/main/res/drawable/ic_destination_flag.xml
  app/src/main/res/drawable/ic_map_my_location.xml
  app/src/main/res/drawable/ic_map_overview.xml
  app/src/main/res/drawable/ic_member_delete.xml
  app/src/main/res/drawable/ic_profile_image.xml
  app/src/main/res/layout/activity_friend.xml
  app/src/main/res/layout/activity_invite.xml
  app/src/main/res/layout/activity_promise_calendar.xml
  app/src/main/res/layout/item_promise_card.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: design

#162 멤버 검색 텍스트 상자 수정, 유저코드 앞에 지도 버튼 아이콘 크기 변경
  app/src/main/java/com/boosters/promise/ui/invite/InviteActivity.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteViewModel.kt
  app/src/main/res/drawable/ic_destination_flag.xml
  app/src/main/res/drawable/ic_map_overview.xml
  app/src/main/res/layout/activity_invite.xml
  app/src/main/res/layout/activity_promise_detail.xml
  app/src/main/res/layout/item_invite_friend.xml
Labels: design

#165 약속 수정, 삭제 시 멤버 데이터 관련 버그 해결
  app/src/main/java/com/boosters/promise/data/member/MemberRepository.kt
  app/src/main/java/com/boosters/promise/data/member/MemberRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/member/source/remote/MemberRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepository.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/receiver/LocationUploadReceiver.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailViewModel.kt
  app/src/main/java/com/boosters/promise/ui/detail/model/PromiseUploadUiState.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingViewModel.kt
Labels: bug, refactor

#172 인터넷 연결 상태 처리, 화면 전환, 약속 없음 카드뷰
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailViewModel.kt
  app/src/main/java/com/boosters/promise/ui/friend/FriendActivity.kt
  app/src/main/java/com/boosters/promise/ui/friend/FriendViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/adapter/PromiseDailyListAdapter.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingViewModel.kt
  app/src/main/res/drawable/ic_promise_empty.xml
  app/src/main/res/layout/item_promise_empty.xml
  app/src/main/res/values/strings.xml
Labels: bug, feature, refactor

#173 가입 화면 로딩 추가, 친구 없음 안내문 다크모드 대응, import 수정
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/signup/SignUpActivity.kt
  app/src/main/res/drawable/ic_friends.xml
Labels: bug, feature

#174 삭제된 약속 삭제 알림으로 접속 시 버그 해결
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepository.kt
  app/src/main/java/com/boosters/promise/data/promise/PromiseRepositoryImpl.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/promise/source/remote/PromiseRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailViewModel.kt
  app/src/main/java/com/boosters/promise/ui/detail/model/PromiseFailUiState.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarActivity.kt
  app/src/main/res/layout/activity_promise_detail.xml
  app/src/main/res/values/strings.xml
Labels: bug

#176 약속 생성, 수정 시 로딩 화면 추가, 로딩 메세지 변경, 지도 크기 유연화
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailActivity.kt
  app/src/main/java/com/boosters/promise/ui/loading/LoadingDialog.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/model/PromiseSettingUiState.kt
  app/src/main/java/com/boosters/promise/ui/signup/SignUpActivity.kt
  app/src/main/res/layout/activity_promise_detail.xml
  app/src/main/res/layout/dialog_loading_progress.xml
  app/src/main/res/values/strings.xml
Labels: feature, design

#177 캘린더 화면 버그 해결
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarActivity.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarViewModel.kt
Labels: bug

#178 친구 검색 탭 버그 해결
  app/src/main/java/com/boosters/promise/ui/friend/FriendActivity.kt
  app/src/main/java/com/boosters/promise/ui/friend/FriendViewModel.kt
Labels: bug

#183 친구 검색 시 멤버를 여러 번 추가할 수 있는 버그 수정, 뒤로가기 버튼 추가, 설정 화면에서 * 표시 수정
  app/src/main/java/com/boosters/promise/ui/invite/InviteActivity.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingActivity.kt
  app/src/main/res/layout/activity_invite.xml
  app/src/main/res/layout/activity_promise_setting.xml
  app/src/main/res/values/strings.xml
Labels: bug, feature, design

#188 약속 상세화면 뷰모델 Unit Test 추가
  app/build.gradle
  app/src/androidTest/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSourceImplTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boosters/promise/data/location/source/remote/LocationRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/member/source/remote/MemberRemoteDataSource.kt
  app/src/main/java/com/boosters/promise/data/user/source/remote/UserRemoteDataSourceImpl.kt
  app/src/main/java/com/boosters/promise/receiver/alarm/AlarmDirector.kt
  app/src/main/java/com/boosters/promise/receiver/alarm/AlarmDirectorImpl.kt
  app/src/main/java/com/boosters/promise/receiver/alarm/AlarmReceiver.kt
  app/src/main/java/com/boosters/promise/receiver/alarm/di/AlarmModule.kt
  app/src/main/java/com/boosters/promise/service/notification/BootService.kt
  app/src/main/java/com/boosters/promise/service/notification/NotificationService.kt
  app/src/main/java/com/boosters/promise/ui/detail/PromiseDetailViewModel.kt
  app/src/main/java/com/boosters/promise/ui/friend/FriendViewModel.kt
  app/src/main/java/com/boosters/promise/ui/invite/InviteViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promisecalendar/PromiseCalendarViewModel.kt
  app/src/main/java/com/boosters/promise/ui/promisesetting/PromiseSettingViewModel.kt
  app/src/main/java/com/boosters/promise/ui/signup/SignUpViewModel.kt
  app/src/main/java/com/boosters/promise/util/NetworkConnectionUtil.kt
  app/src/test/java/com/boosters/promise/ui/detail/PromiseDetailViewModelTest.kt
Labels: feature, refactor
